### ISSUE TITLE
Dear Ahour, I found that there is a file called 'categories_vg_478_130.json' lost which is the cats_path.

### ISSUE THREAD

**Issue by UlanqabBadGuy** [jinghanSunn/Few-weak-shot-RG#2]
Hi, can I get that file from you. I want to test some pictures acccording to yours. Thank you very much.

**Comment by jinghanSunn** [comment]
Hi, 'categories_vg_478_130.json' is a file used for coco/voc/vgg dataset. This repository is implemented for medical datasets. If you want to test coco/voc/vgg, please download these datasets from the official websites.

**Comment by UlanqabBadGuy** [comment]
okay, thanks for your explanation.

**Comment by UlanqabBadGuy** [comment]
okay, thanks for your explanation.
